# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc3f35426ec5b129c36e572c300f8f4899f5712b54076ce84eb0ae4990719219f4b5e10de35d5b2e7709ec3ca04afb8415289fc36d945e8828a0e8762a1ac6b6

test:
  secret_key_base: 152fa38a26669aec130bd9dfb548b5a7c6c9fa0c092d4b5de852ade8408d5b2ebbee05f6fda3fd28a0de30e8cef846511c26d4a5b3fe6fc2e54f0f8a524374a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
